"""What the instrument may assume about a caller's tree — and how a caller says otherwise.

Round STRANGER-GUARDS (publicization batch C): two families of fact were hard-coded to the
first caller's layout, each measured biting before it moved here.

* **Which repository a command targets.** Twelve call sites defaulted it by directory depth
  (`run_dir.parents[3]`) or to the bare cwd — right on the first caller's layout, silently
  wrong one directory down or one layout over. `discover_repo_root` asks git instead and
  refuses loudly when git has no answer: a wrong root taken quietly is the defect class,
  not a convenience.

* **Where records and specifications live.** `candidate_path_check` exempts records (they
  quote the broken paths they report) and specifications (they name files required not to
  exist yet); `review_freeze_check` admits only returned records while `E9`'s window is
  open. Both surfaces are the *caller's* layout, not the instrument's: the hard-coded
  `ResearchSystem/…` prefixes were the first caller's directory names, so a second caller's
  records would be scanned as work products and its returned record blocked from landing —
  rider `chk-caller-prefixes` banked that replay of the `freeze-audit` deadlock, and rider
  `submod-index`'s false blocks are the sibling shape. The surfaces are now a declaration
  in the caller's own `.harness/scan-surfaces.json` — written with the defaults below by
  `dtw init`, read by both guards; the first caller's entries live on as *its* declaration,
  not as anybody's truth.

A declaration that cannot be read as declared is **refused loudly by the guards, never
silently replaced by defaults**: a typo that quietly reverted the surfaces would re-scan a
caller's records, which is the exact failure the declaration exists to end.
"""
from __future__ import annotations

import dataclasses
import json
import pathlib
import subprocess

from rsclib.document_harness import SpecGap

#: The declaration's path inside a caller, shown in refusals. `.harness/` is the harness's
#: caller-side directory and is conventionally gitignored; like every hook and the
#: `core.hooksPath` that runs them, the declaration is per-checkout state, regenerated by
#: `dtw init` (which refuses to overwrite one that exists — a caller's edits survive).
DECLARATION = ".harness/scan-surfaces.json"

#: The defaults cover the layout `dtw init` creates plus the conventions the procedure
#: states: the rider bank `init` copies to the target's root, the per-round `journal/`
#: ONBOARDING item 5 names (deliberately not pre-created), the migration directory
#: `REVIEW.md`'s record channel names for returned records, and an `assurance/runs/` tree
#: for the control planes a run's instruction is required to create.
DEFAULT_RECORD_SURFACE = ("HARNESS-RIDERS.md", "journal/")
DEFAULT_REVIEW_RECORD_DIRS = ("migration/document-work-assurance-v3/",)
DEFAULT_SPECIFICATION_SURFACE = ("assurance/runs/",)


@dataclasses.dataclass(frozen=True)
class ScanSurfaces:
    """The three caller-declarable surfaces, as prefix strings from the repository root.

    An entry ending in `/` is a whole tree; any other entry matches by leading string, the
    same rule the guards have always applied. `record` may quote broken paths and is not
    scanned by the candidate lint; `review_record_dirs` is where the four `v3-*` record
    families land, admitted by the freeze guard and likewise unscanned; `specification` is
    the runs tree — instructions there name files that cannot exist at freeze time, and a
    run's returned ReviewResult JSONs live under it.
    """

    record: tuple[str, ...]
    review_record_dirs: tuple[str, ...]
    specification: tuple[str, ...]


DEFAULTS = ScanSurfaces(
    record=DEFAULT_RECORD_SURFACE,
    review_record_dirs=DEFAULT_REVIEW_RECORD_DIRS,
    specification=DEFAULT_SPECIFICATION_SURFACE,
)

#: Declaration key -> ScanSurfaces field. A key absent from the declaration keeps its
#: default; a key outside this map is refused, because a misspelled key silently ignored
#: would be the quiet fallback the module docstring forbids.
_KEYS = {
    "record_surface": "record",
    "review_record_dirs": "review_record_dirs",
    "specification_surface": "specification",
}


class SurfaceDeclarationError(ValueError):
    """`.harness/scan-surfaces.json` exists but cannot be read as declared."""


def load_scan_surfaces(repo_root: pathlib.Path | str) -> ScanSurfaces:
    """The caller's declared surfaces; `DEFAULTS` when no declaration file exists.

    Raises `SurfaceDeclarationError` — never falls back — when a declaration exists but is
    not one JSON object of known keys, each a list of non-empty strings.
    """
    path = pathlib.Path(repo_root) / ".harness" / "scan-surfaces.json"
    if not path.is_file():
        return DEFAULTS
    try:
        declared = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise SurfaceDeclarationError(f"{DECLARATION} is not readable JSON: {exc}") from exc
    if not isinstance(declared, dict):
        raise SurfaceDeclarationError(
            f"{DECLARATION} must hold one JSON object, not {type(declared).__name__}"
        )
    unknown = sorted(set(declared) - set(_KEYS))
    if unknown:
        raise SurfaceDeclarationError(
            f"{DECLARATION} declares no such surface: {', '.join(unknown)} "
            f"(the keys are {', '.join(sorted(_KEYS))})"
        )
    fields: dict[str, tuple[str, ...]] = {}
    for key, field in _KEYS.items():
        if key not in declared:
            fields[field] = getattr(DEFAULTS, field)
            continue
        entries = declared[key]
        if not isinstance(entries, list) or not all(
            isinstance(entry, str) and entry for entry in entries
        ):
            raise SurfaceDeclarationError(
                f"{DECLARATION} {key} must be a list of non-empty strings"
            )
        fields[field] = tuple(entries)
    return ScanSurfaces(**fields)


def render_declaration(surfaces: ScanSurfaces = DEFAULTS) -> str:
    """The declaration file's bytes for these surfaces — what `dtw init` writes."""
    return (
        json.dumps(
            {key: list(getattr(surfaces, field)) for key, field in _KEYS.items()},
            indent=1,
        )
        + "\n"
    )


def discover_repo_root(start: pathlib.Path | str) -> pathlib.Path:
    """The toplevel of the git work tree holding `start` — or a refusal, never a guess.

    Replaces the cwd and `parents[3]` defaults (round STRANGER-GUARDS): both resolved a
    *plausible* directory whether or not it was the repository the command was about, and a
    wrong root taken quietly mis-writes the freeze marker, mis-derives control roots, and
    mis-reads every root-relative path. git's answer is right at any depth and in either
    repository of a submodule mount; where git has none, `SpecGap` carries the refusal.
    """
    start = pathlib.Path(start)
    probe = start if start.is_dir() else start.parent
    out = subprocess.run(
        ["git", "-C", str(probe), "rev-parse", "--show-toplevel"],
        check=False,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    top = out.stdout.decode("utf-8", errors="replace").strip()
    if out.returncode != 0 or not top:
        raise SpecGap(
            f"no repository root was given and {probe} is not inside a git work tree; "
            "pass --repo-root explicitly"
        )
    return pathlib.Path(top).resolve()
