"""What the instrument may assume about a caller's tree — and how a caller says otherwise.

Round STRANGER-GUARDS (publicization batch C): two families of fact were hard-coded to the
first caller's layout, each measured biting before it moved here.

* **Which repository a command targets.** Twelve call sites defaulted it by directory depth
  (`run_dir.parents[3]`) or to the bare cwd — right on the first caller's layout, silently
  wrong one directory down or one layout over. `discover_repo_root` asks git instead and
  refuses loudly when git has no answer: a wrong root taken quietly is the defect class,
  not a convenience.

* **Where records and specifications live.** `candidate_path_check` exempts records (they
  quote the broken paths they report) and specifications (they name files required not to
  exist yet); `review_freeze_check` admits only returned records while `E9`'s window is
  open. Both surfaces are the *caller's* layout, not the instrument's: the hard-coded
  `ResearchSystem/…` prefixes were the first caller's directory names, so a second caller's
  records would be scanned as work products and its returned record blocked from landing —
  rider `chk-caller-prefixes` banked that replay of the `freeze-audit` deadlock, and rider
  `submod-index`'s false blocks are the sibling shape. The surfaces are now a declaration
  in the caller's own `.harness/scan-surfaces.json` — written with the defaults below by
  `dtw init`, read by both guards; the first caller's entries live on as *its* declaration,
  not as anybody's truth.

A declaration that cannot be read as declared is **refused loudly by the guards, never
silently replaced by defaults**: a typo that quietly reverted the surfaces would re-scan a
caller's records, which is the exact failure the declaration exists to end.
"""
from __future__ import annotations

import dataclasses
import json
import pathlib
import subprocess

from rsclib.document_harness import SpecGap
from rsclib.document_harness.paths import env_without_repo_scope

#: The declaration's path inside a caller, shown in refusals. `.harness/` is the harness's
#: caller-side directory and is conventionally gitignored; like every hook and the
#: `core.hooksPath` that runs them, the declaration is per-checkout state, regenerated by
#: `dtw init` (which refuses to overwrite one that exists — a caller's edits survive).
DECLARATION = ".harness/scan-surfaces.json"

#: The defaults cover the layout `dtw init` creates plus the conventions the procedure
#: states: the rider bank `init` copies to the target's root, the per-round `journal/`
#: ONBOARDING item 5 names (deliberately not pre-created), the review-records directory
#: `REVIEW.md`'s record channel names for returned records, and an `assurance/runs/` tree
#: for the control planes a run's instruction is required to create.
#:
#: `DEFAULT_REVIEW_RECORD_DIRS` held `migration/document-work-assurance-v3/` until round
#: `CORE-SET-CODE` (2026-08-27, user ruling 7). That was never a convention: it was the
#: directory *this instrument's own* construction records happen to live in, carrying this
#: repository's own history into every caller's factory setting — the same
#: first-caller-layout defect round STRANGER-GUARDS closed one field over. The value moves
#: and the identifier does not (user ruling 24), because renaming the identifier would
#: change nothing for any caller and the point of the ruling is that something changes.
#:
#: **Migration, and it bites at once rather than on the next clone.** `dtw init` writes the
#: defaults into the declaration, and `.harness/` is conventionally gitignored — so a caller
#: that never ran `init`, or that lost `.harness/` to a fresh clone, has no declaration and
#: is running on the values above. If such a caller keeps returned review records under the
#: old directory, this change stops both guards recognising them from the moment the mount
#: advances: `candidate_path_check` scans them as work products, and `review_freeze_check`
#: refuses to admit the one commit `E9`'s window allows. The fix is one line in the caller's
#: own tree and nothing in the instrument's — declare `review_record_dirs` with the
#: directory the records are actually in, which is the adaptation `HD-34` asks a caller to
#: record rather than the in-place instrument edit `HD-34` forbids. This instrument writes
#: no caller's tree (user ruling 25); the advice is stated here and in `ONBOARDING.md`, and
#: the caller applies it when it chooses to.
DEFAULT_RECORD_SURFACE = ("HARNESS-RIDERS.md", "journal/")
DEFAULT_REVIEW_RECORD_DIRS = ("assurance/review-records/",)
DEFAULT_SPECIFICATION_SURFACE = ("assurance/runs/",)


@dataclasses.dataclass(frozen=True)
class ScanSurfaces:
    """The three caller-declarable surfaces, as prefix strings from the repository root.

    A `record` entry ending in `/` is a whole tree; any other matches by leading string —
    the field holds file entries (`HARNESS-RIDERS.md`) as well as trees. The other two
    fields name whole trees only, so their entries are normalized to `/`-terminated here,
    where the groups are built: every matcher either guard composes from them then reads
    one declaration one way. Before that (FULL `c2e955b` L-1) a slash-less entry was
    accepted by the loader yet read divergently — the candidate lint exempted the tree by
    leading string while the freeze guard's result matcher required the slash
    structurally, blocking the run's returned ReviewResult during `E9`'s window.

    `record` may quote broken paths and is not scanned by the candidate lint;
    `review_record_dirs` is where the four `v3-*` record families land, admitted by the
    freeze guard and likewise unscanned; `specification` is the runs tree — instructions
    there name files that cannot exist at freeze time, and a run's returned ReviewResult
    JSONs live under it.
    """

    record: tuple[str, ...]
    review_record_dirs: tuple[str, ...]
    specification: tuple[str, ...]

    def __post_init__(self) -> None:
        for field in ("review_record_dirs", "specification"):
            entries = getattr(self, field)
            normalized = tuple(e if e.endswith("/") else e + "/" for e in entries)
            if normalized != entries:
                object.__setattr__(self, field, normalized)


DEFAULTS = ScanSurfaces(
    record=DEFAULT_RECORD_SURFACE,
    review_record_dirs=DEFAULT_REVIEW_RECORD_DIRS,
    specification=DEFAULT_SPECIFICATION_SURFACE,
)

#: Declaration key -> ScanSurfaces field. A key absent from the declaration keeps its
#: default; a key outside this map is refused, because a misspelled key silently ignored
#: would be the quiet fallback the module docstring forbids.
_KEYS = {
    "record_surface": "record",
    "review_record_dirs": "review_record_dirs",
    "specification_surface": "specification",
}


class SurfaceDeclarationError(ValueError):
    """`.harness/scan-surfaces.json` exists but cannot be read as declared."""


def load_scan_surfaces(repo_root: pathlib.Path | str) -> ScanSurfaces:
    """The caller's declared surfaces; `DEFAULTS` when no declaration file exists.

    Raises `SurfaceDeclarationError` — never falls back — when a declaration exists but is
    not one JSON object of known keys, each a list of non-empty strings.
    """
    path = pathlib.Path(repo_root) / ".harness" / "scan-surfaces.json"
    if not path.is_file():
        return DEFAULTS
    try:
        declared = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise SurfaceDeclarationError(f"{DECLARATION} is not readable JSON: {exc}") from exc
    if not isinstance(declared, dict):
        raise SurfaceDeclarationError(
            f"{DECLARATION} must hold one JSON object, not {type(declared).__name__}"
        )
    unknown = sorted(set(declared) - set(_KEYS))
    if unknown:
        raise SurfaceDeclarationError(
            f"{DECLARATION} declares no such surface: {', '.join(unknown)} "
            f"(the keys are {', '.join(sorted(_KEYS))})"
        )
    fields: dict[str, tuple[str, ...]] = {}
    for key, field in _KEYS.items():
        if key not in declared:
            fields[field] = getattr(DEFAULTS, field)
            continue
        entries = declared[key]
        if not isinstance(entries, list) or not all(
            isinstance(entry, str) and entry for entry in entries
        ):
            raise SurfaceDeclarationError(
                f"{DECLARATION} {key} must be a list of non-empty strings"
            )
        fields[field] = tuple(entries)
    return ScanSurfaces(**fields)


def render_declaration(surfaces: ScanSurfaces = DEFAULTS) -> str:
    """The declaration file's bytes for these surfaces — what `dtw init` writes."""
    return (
        json.dumps(
            {key: list(getattr(surfaces, field)) for key, field in _KEYS.items()},
            indent=1,
        )
        + "\n"
    )


#: The caller's own tracked declaration, at its repository root: which rule files it adds to
#: the harness's own instruction layer, and where its policy file is. Tracked, unlike
#: `.harness/scan-surfaces.json` beside it — a fresh clone must still receive it, because the
#: files it names are read by people and by cold sessions, not only by this checkout's guards.
HARNESS_CONFIG = "harness.json"


@dataclasses.dataclass(frozen=True)
class HarnessConfig:
    """`harness.json`, as E10's second sentence describes it: two fields, both paths.

    `policy` is the caller's policy file — the one `ORCHESTRATION.md`'s *Reading the caller's
    policy file* addresses — or `None` where the caller has written none, which that section
    says is not a defect. `rules` are the caller's own rule files: `dtw dispatch` names them
    in the prompt it writes, and both `layer_path_check.py` and `sweep_refs.py` scan them as
    they scan the members. A declared rule binds only the repository declaring it.

    Paths only. Rule and policy text stay markdown so that a person and a cold session read
    the same bytes; a config that carried the rules themselves would be a second copy of them.
    """

    policy: str | None
    rules: tuple[str, ...]


DEFAULT_HARNESS_CONFIG = HarnessConfig(policy=None, rules=())


class HarnessConfigError(ValueError):
    """`harness.json` exists but cannot be read as declared."""


def load_harness_config(repo_root: pathlib.Path | str) -> HarnessConfig:
    """The repository's declared rules and policy; `DEFAULT_HARNESS_CONFIG` when absent.

    Absent is a real answer and not an error: a repository that declares nothing adds no
    rules and has no policy file, which is exactly what the defaults say. Present but
    unreadable is refused loudly — never silently defaulted — for the reason the module
    docstring gives one field over: a typo that quietly emptied `rules` would stop both
    guards scanning a caller's rule files while every check still passed green.
    """
    path = pathlib.Path(repo_root) / HARNESS_CONFIG
    if not path.is_file():
        return DEFAULT_HARNESS_CONFIG
    try:
        declared = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise HarnessConfigError(f"{HARNESS_CONFIG} is not readable JSON: {exc}") from exc
    if not isinstance(declared, dict):
        raise HarnessConfigError(
            f"{HARNESS_CONFIG} must hold one JSON object, not {type(declared).__name__}"
        )
    unknown = sorted(set(declared) - {"policy", "rules"})
    if unknown:
        raise HarnessConfigError(
            f"{HARNESS_CONFIG} declares no such field: {', '.join(unknown)} "
            "(the fields are policy, rules)"
        )
    policy = declared.get("policy")
    if policy is not None and not (isinstance(policy, str) and policy):
        raise HarnessConfigError(
            f"{HARNESS_CONFIG} policy must be a non-empty string or null"
        )
    rules = declared.get("rules", [])
    if not isinstance(rules, list) or not all(
        isinstance(entry, str) and entry for entry in rules
    ):
        raise HarnessConfigError(f"{HARNESS_CONFIG} rules must be a list of non-empty strings")
    return HarnessConfig(policy=policy, rules=tuple(rules))


def render_harness_config(config: HarnessConfig = DEFAULT_HARNESS_CONFIG) -> str:
    """The config file's bytes — what `dtw init` writes, empty by default.

    Empty rather than guessed: which rules a repository adds and where its policy lives are
    both judgment, and `init` writes only the mechanical half. Both fields are emitted even
    when empty, because the file is also how a caller discovers what it may declare.
    """
    return (
        json.dumps({"policy": config.policy, "rules": list(config.rules)}, indent=1)
        + "\n"
    )


def discover_repo_root(start: pathlib.Path | str) -> pathlib.Path:
    """The toplevel of the git work tree holding `start` — or a refusal, never a guess.

    Replaces the cwd and `parents[3]` defaults (round STRANGER-GUARDS): both resolved a
    *plausible* directory whether or not it was the repository the command was about, and a
    wrong root taken quietly mis-writes the freeze marker, mis-derives control roots, and
    mis-reads every root-relative path. git's answer is right at any depth and in either
    repository of a submodule mount; where git has none, `SpecGap` carries the refusal.

    **The environment is cleared of the caller's repository first** (round SUBMOD-HOOKENV
    closed the same class one site over, in `_submodule_files`): git obeys `GIT_WORK_TREE`
    and `GIT_DIR` over `-C`, so under a hook — or any process git started — the answer is
    about the *environment's* repository, not the probe's. Measured on one super+mount
    tree: without the variable `discover_repo_root('mount')` answers `…/super/mount`, with
    `GIT_WORK_TREE=…/super` it answers `…/super`, neither raising. A git that cannot name
    those variables refuses here rather than asking uncleared, because an answer taken from
    the wrong repository is exactly what this function exists to stop.
    """
    start = pathlib.Path(start)
    probe = start if start.is_dir() else start.parent
    env = env_without_repo_scope()
    if env is None:
        raise SpecGap(
            "git cannot name its own repository-scoping variables "
            "(`git rev-parse --local-env-vars` failed), so the repository holding "
            f"{probe} cannot be asked for safely; pass --repo-root explicitly"
        )
    out = subprocess.run(
        ["git", "-C", str(probe), "rev-parse", "--show-toplevel"],
        check=False,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        env=env,
    )
    top = out.stdout.decode("utf-8", errors="replace").strip()
    if out.returncode != 0 or not top:
        raise SpecGap(
            f"no repository root was given and {probe} is not inside a git work tree; "
            "pass --repo-root explicitly"
        )
    return pathlib.Path(top).resolve()
